### ISSUE TITLE
spinster won't run from the global nvm install location

### ISSUE THREAD

**Issue by lineus** [lineus/tools#1]
```
Pro-bin: spinster 
/Users/lineus/.nvm/versions/node/v8.9.4/lib/node_modules/spinster/index.js:4
import MongodbMemoryServer from 'mongodb-memory-server'
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/lineus/.nvm/versions/node/v8.9.4/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at Object.<anonymous> (/Users/lineus/.nvm/versions/node/v8.9.4/lib/node_modules/babel-cli/lib/_babel-node.js:154:22)
Pro-bin: 
```
this is babel-node not seeing the env preset. I can run it thusly:
```
Pro-bin: cd ../lib/node_modules/spinster/
Pro-spinster: babel-node -- ./index.js run -V 3.4.4 -p /Users/lineus/dev/node/Help/test/mongo
connected
^C
Pro-spinster: 
```
fix this shit.

**Comment by lineus** [comment]
instead of relying on babel-node to run it, I just have to add a build step that uses babel to compile it and then publish the result.
